baseURL = 'https://www.kriegeterna.com/'
languageCode = 'en-us'
title = 'Krieg Eterna'
disableKinds = ["RSS"]

[services]
  [services.rss]
    limit = 10

[params]
  favicon = "/favicon.ico"
  stylesheet = "/style.css"
  indexarticles = 50
  taglist = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
